import type { Metadata } from 'next';
import cn from 'classnames';
import { PopupProvider } from '@/context';
import { PopupRoot } from '@/layout';

import '@/styles/style.scss';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body>
                <PopupProvider>
                    <div className="container">{children}</div>

                    <PopupRoot />
                </PopupProvider>
            </body>
        </html>
    );
}
